### ISSUE TITLE
Borderlands 2's Freecam doesn't seem to work on the current Steam version

### ISSUE THREAD

**Issue by FuckingStealingNames** [framedsc/Sitesource#196]
When attempting to enable Freecam at any point while injected to the game, it will hang up CE and refuse to enable itself.
Possibly something changed internally to make it unable to be ran.

**Comment by originalnicodr** [comment]
That is odd, don't think the [.exe has been updated](https://steamdb.info/app/49520/patchnotes/) since the guide was uploaded [on April 7th 2019](https://github.com/framedsc/Sitesource/commit/d393970278ee4823b838336b8fcbda32c76d59b2).

@jim2point0 since you wrote the guide, any idea what could be happening here? Dont really expect you to remember how a 5yo cheat table you made works, but figured I could ask 😛 

Alternatively you could look up how to use UE3 console and keybindings to shoot it

**Comment by originalnicodr** [comment]
Hey, found [this mod](https://bl-sdk.github.io/mods/Photomode/), maybe it helps.

**Comment by FuckingStealingNames** [comment]
That mod does the job, yeah.

**Comment by originalnicodr** [comment]
Since I doubt the author will ever fix the cheat table I added an alert box explaining the guide is outdated and linked the pm mod and the cheats mod (c32fa7d). Will close this issue for now, but feel free to update the guide with these tools or new tips if you feel like it!
